package com.vicipaw.appmanager

import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.ImageView
import android.widget.TextView
import androidx.recyclerview.widget.DiffUtil
import androidx.recyclerview.widget.ListAdapter
import androidx.recyclerview.widget.RecyclerView
import com.google.android.material.button.MaterialButton

/**
 * Adapter for displaying applications using ListAdapter and DiffUtil.
 * Generated by AI.
 */
class AppAdapter(
    private val onOpenClick: (AppInfo) -> Unit,
    private val onInfoClick: (AppInfo) -> Unit
) : ListAdapter<AppInfo, AppAdapter.AppViewHolder>(AppDiffCallback()) {

    inner class AppViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
        val ivAppIcon: ImageView = itemView.findViewById(R.id.ivAppIcon)
        val tvAppName: TextView = itemView.findViewById(R.id.tvAppName)
        val tvPackageName: TextView = itemView.findViewById(R.id.tvPackageName)
        val tvSystemBadge: TextView = itemView.findViewById(R.id.tvSystemBadge)
        val tvPinnedBadge: TextView = itemView.findViewById(R.id.tvPinnedBadge)
        val btnOpen: MaterialButton = itemView.findViewById(R.id.btnOpen)
        val btnInfo: MaterialButton = itemView.findViewById(R.id.btnInfo)
    }

    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): AppViewHolder {
        val view = LayoutInflater.from(parent.context)
            .inflate(R.layout.item_app, parent, false)
        return AppViewHolder(view)
    }

    override fun onBindViewHolder(holder: AppViewHolder, position: Int) {
        val app = getItem(position)

        holder.ivAppIcon.setImageDrawable(app.icon)
        holder.tvAppName.text = app.appName
        holder.tvPackageName.text = app.packageName

        holder.tvSystemBadge.visibility = if (app.isSystemApp) View.VISIBLE else View.GONE
        holder.tvPinnedBadge.visibility = if (app.isPinned) View.VISIBLE else View.GONE

        holder.btnOpen.setOnClickListener { onOpenClick(app) }
        holder.btnInfo.setOnClickListener { onInfoClick(app) }
    }

    class AppDiffCallback : DiffUtil.ItemCallback<AppInfo>() {
        override fun areItemsTheSame(oldItem: AppInfo, newItem: AppInfo): Boolean {
            return oldItem.packageName == newItem.packageName
        }

        override fun areContentsTheSame(oldItem: AppInfo, newItem: AppInfo): Boolean {
            return oldItem.appName == newItem.appName &&
                    oldItem.isSystemApp == newItem.isSystemApp &&
                    oldItem.isPinned == newItem.isPinned
        }
    }
}
