package com.vicipaw.appmanager

import android.graphics.drawable.Drawable

/**
 * Data class representing an application item.
 * Generated by AI.
 */
data class AppInfo(
    val appName: String,
    val packageName: String,
    val icon: Drawable,
    val isSystemApp: Boolean,
    var isPinned: Boolean = false
)
