package com.vicipaw.appmanager

import android.app.ActivityManager
import android.content.Context
import android.content.Intent
import android.content.pm.ApplicationInfo
import android.content.pm.PackageManager
import android.graphics.Canvas
import android.graphics.Paint
import android.graphics.RectF
import android.graphics.Typeface
import android.net.Uri
import android.os.Bundle
import android.provider.Settings
import android.text.Editable
import android.text.TextWatcher
import android.view.View
import android.widget.TextView
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import androidx.core.content.ContextCompat
import androidx.recyclerview.widget.ItemTouchHelper
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView
import com.google.android.material.floatingactionbutton.FloatingActionButton
import com.google.android.material.progressindicator.LinearProgressIndicator
import com.google.android.material.switchmaterial.SwitchMaterial
import com.google.android.material.textfield.TextInputEditText
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

/**
 * Main Activity for Delook App Manager.
 * Generated by AI.
 */
class MainActivity : AppCompatActivity() {

    private lateinit var recyclerView: RecyclerView
    private lateinit var etSearch: TextInputEditText
    private lateinit var switchSystemApps: SwitchMaterial
    private lateinit var progressBar: LinearProgressIndicator
    private lateinit var tvAppCount: TextView
    private lateinit var tvSharedLink: TextView
    private lateinit var layoutEmpty: View
    private lateinit var fabClearRecents: FloatingActionButton

    private lateinit var adapter: AppAdapter
    private var allApps: List<AppInfo> = emptyList()
    private var sharedLinkUrl: String? = null
    private val prefs by lazy { getSharedPreferences("delook_prefs", Context.MODE_PRIVATE) }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        recyclerView    = findViewById(R.id.recyclerView)
        etSearch        = findViewById(R.id.etSearch)
        switchSystemApps = findViewById(R.id.switchSystemApps)
        progressBar     = findViewById(R.id.progressBar)
        tvAppCount      = findViewById(R.id.tvAppCount)
        tvSharedLink    = findViewById(R.id.tvSharedLink)
        layoutEmpty     = findViewById(R.id.layoutEmpty)
        fabClearRecents = findViewById(R.id.fabClearRecents)

        setupRecyclerView()
        setupListeners()
        setupSwipeToPin()
        handleIncomingIntent(intent)
        loadApps()
    }

    override fun onNewIntent(intent: Intent?) {
        super.onNewIntent(intent)
        intent?.let { handleIncomingIntent(it) }
    }

    private fun setupRecyclerView() {
        adapter = AppAdapter(
            onOpenClick = { appInfo -> openApp(appInfo) },
            onInfoClick = { appInfo -> openAppInfo(appInfo) }
        )
        recyclerView.apply {
            layoutManager = LinearLayoutManager(this@MainActivity)
            adapter = this@MainActivity.adapter
        }
    }

    private fun setupSwipeToPin() {
        val swipeHandler = object : ItemTouchHelper.SimpleCallback(0, ItemTouchHelper.LEFT) {
            override fun onMove(rv: RecyclerView, vh: RecyclerView.ViewHolder, target: RecyclerView.ViewHolder) = false

            override fun onSwiped(viewHolder: RecyclerView.ViewHolder, direction: Int) {
                val position = viewHolder.adapterPosition
                if (position == RecyclerView.NO_POSITION) return
                
                val currentList = adapter.currentList
                if (position >= currentList.size) {
                    adapter.notifyDataSetChanged()
                    return
                }

                val app = currentList[position]
                val indexInAllApps = allApps.indexOfFirst { it.packageName == app.packageName }
                
                if (indexInAllApps != -1) {
                    val oldApp = allApps[indexInAllApps]
                    val newApp = oldApp.copy(isPinned = !oldApp.isPinned)
                    val newAllApps = allApps.toMutableList()
                    newAllApps[indexInAllApps] = newApp
                    allApps = newAllApps

                    val pinnedSet = prefs.getStringSet("pinned_apps", mutableSetOf())?.toMutableSet() ?: mutableSetOf()
                    if (newApp.isPinned) pinnedSet.add(app.packageName) else pinnedSet.remove(app.packageName)
                    prefs.edit().putStringSet("pinned_apps", pinnedSet).apply()

                    applyFilter()
                } else {
                    adapter.notifyItemChanged(position)
                }
            }

            override fun onChildDraw(c: Canvas, rv: RecyclerView, vh: RecyclerView.ViewHolder, dX: Float, dY: Float, s: Int, a: Boolean) {
                val itemView = vh.itemView
                val paint = Paint()
                val position = vh.adapterPosition
                
                if (dX < 0 && position != RecyclerView.NO_POSITION && position < adapter.currentList.size) {
                    paint.color = ContextCompat.getColor(this@MainActivity, R.color.colorAccent)
                    val background = RectF(itemView.right.toFloat() + dX, itemView.top.toFloat(), itemView.right.toFloat(), itemView.bottom.toFloat())
                    c.drawRect(background, paint)

                    val app = adapter.currentList[position]
                    val text = if (app.isPinned) getString(R.string.btn_unpin) else getString(R.string.pinned_app_badge)
                    
                    paint.color = android.graphics.Color.WHITE
                    paint.textSize = 40f
                    paint.typeface = Typeface.DEFAULT_BOLD
                    paint.textAlign = Paint.Align.CENTER
                    
                    val textX = itemView.right - 100f
                    val textY = itemView.top + (itemView.height / 2f) + 15f
                    c.drawText(text, textX, textY, paint)
                }
                super.onChildDraw(c, rv, vh, dX, dY, s, a)
            }
        }
        ItemTouchHelper(swipeHandler).attachToRecyclerView(recyclerView)
    }

    private fun setupListeners() {
        etSearch.addTextChangedListener(object : TextWatcher {
            override fun beforeTextChanged(s: CharSequence?, start: Int, count: Int, after: Int) {}
            override fun onTextChanged(s: CharSequence?, start: Int, before: Int, count: Int) {}
            override fun afterTextChanged(s: Editable?) { applyFilter() }
        })
        switchSystemApps.setOnCheckedChangeListener { _, _ -> applyFilter() }
        
        fabClearRecents.setOnClickListener {
            clearBackgroundProcesses()
        }
    }

    private fun clearBackgroundProcesses() {
        val am = getSystemService(Context.ACTIVITY_SERVICE) as ActivityManager
        val pm = packageManager
        val packages = pm.getInstalledApplications(0)
        
        for (app in packages) {
            if (app.packageName != packageName && (app.flags and ApplicationInfo.FLAG_SYSTEM) == 0) {
                am.killBackgroundProcesses(app.packageName)
            }
        }
        
        Toast.makeText(this, "Refreshing system...", Toast.LENGTH_SHORT).show()
    }

    private fun handleIncomingIntent(intent: Intent) {
        if (intent.action == Intent.ACTION_SEND && intent.type == "text/plain") {
            val sharedText = intent.getStringExtra(Intent.EXTRA_TEXT)
            if (!sharedText.isNullOrBlank()) {
                sharedLinkUrl = sharedText
                tvSharedLink.visibility = View.VISIBLE
                tvSharedLink.text = "🔗 $sharedText"
            }
        }
    }

    private fun loadApps() {
        progressBar.visibility = View.VISIBLE
        CoroutineScope(Dispatchers.Main).launch {
            val pinnedApps = prefs.getStringSet("pinned_apps", emptySet()) ?: emptySet()
            allApps = withContext(Dispatchers.IO) { fetchInstalledApps(pinnedApps) }
            progressBar.visibility = View.GONE
            applyFilter()
        }
    }

    private fun fetchInstalledApps(pinnedApps: Set<String>): List<AppInfo> {
        val pm = packageManager
        @Suppress("DEPRECATION")
        val installedApps = pm.getInstalledApplications(PackageManager.GET_META_DATA)
        return installedApps.mapNotNull { appInfo ->
            try {
                AppInfo(
                    appName = pm.getApplicationLabel(appInfo).toString(),
                    packageName = appInfo.packageName,
                    icon = pm.getApplicationIcon(appInfo.packageName),
                    isSystemApp = (appInfo.flags and ApplicationInfo.FLAG_SYSTEM) != 0,
                    isPinned = pinnedApps.contains(appInfo.packageName)
                )
            } catch (e: PackageManager.NameNotFoundException) { null }
        }
    }

    private fun applyFilter() {
        val showSystem = switchSystemApps.isChecked
        val query = etSearch.text?.toString()?.trim()?.lowercase() ?: ""
        val filtered = allApps.filter { app ->
            val passSystemFilter = showSystem || !app.isSystemApp || app.isPinned
            val passSearchFilter = query.isEmpty() || app.appName.lowercase().contains(query) || app.packageName.lowercase().contains(query)
            passSystemFilter && passSearchFilter
        }.sortedWith(compareByDescending<AppInfo> { it.isPinned }.thenBy { it.isSystemApp }.thenBy { it.appName.lowercase() })

        adapter.submitList(filtered)
        tvAppCount.text = "${filtered.size}"
        layoutEmpty.visibility = if (filtered.isEmpty()) View.VISIBLE else View.GONE
        recyclerView.visibility = if (filtered.isEmpty()) View.GONE else View.VISIBLE
    }

    private fun openApp(app: AppInfo) {
        val launchIntent = packageManager.getLaunchIntentForPackage(app.packageName)
        if (launchIntent != null) {
            launchIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            startActivity(launchIntent)
        } else {
            Toast.makeText(this, getString(R.string.cannot_open_app) + "\n${app.appName}", Toast.LENGTH_SHORT).show()
        }
    }

    private fun openAppInfo(app: AppInfo) {
        val intent = Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS).apply {
            data = Uri.fromParts("package", app.packageName, null)
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        }
        try { startActivity(intent) } catch (e: Exception) {
            Toast.makeText(this, "Cannot open info: ${app.appName}", Toast.LENGTH_SHORT).show()
        }
    }
}
